Add support for DSP 7265 Lockin
PyMoDAQ/pymodaq_plugins_signal_recovery pull request #4
Opened 2024-11-28 10:59 UTC by louisld

Add actuator (differential measurement not supported yet) and 0D viewer for the DSP 7265 lockin.

2024-11-29 15:33 UTC, seb5g commented
Hello,
are you ready for a review of your code?

2024-11-29 15:36 UTC, seb5g commented
make sure to introduce lock mechanism as you produced both an actuator and a detector using the same ressource (controller) communicating using serial com but without any thread safe  communication protocol. Let me know if you want examples!

2024-11-29 17:04 UTC, louisld commented
Ok I will try to implement lock mechanism.

I am interested if you have few examples.

2024-12-01 08:19 UTC, seb5g commented
You can look at the newport plugin package:

![image](https://github.com/user-attachments/assets/088b2b35-aae2-4bf5-8b49-8f4a85b0ffa8)

![image](https://github.com/user-attachments/assets/802b239f-b0c2-490e-9b3f-341bc6da2314)

2024-12-02 17:12 UTC, louisld commented
I created a new class inherited from pymeasure that makes read and write functions thread safe.

2024-12-02 19:25 UTC, seb5g requested changes
good job but quite a bit of mixed up things I highlighted. Look at a recent version of the plugin template please

2024-12-02 19:25 UTC, seb5g commented on src/pymodaq_plugins_signal_recovery/daq_move_plugins/daq_move_Lockin_DSP7265.py
> +        {'title': 'MultiAxes:', 'name': 'multiaxes', 'type': 'group',
you should follow the template and not add manually these settings

2024-12-02 19:25 UTC, seb5g commented on src/pymodaq_plugins_signal_recovery/daq_move_plugins/daq_move_Lockin_DSP7265.py
> +    def get_actuator_value(self) -> float:
the returned type is DataActuator

2024-12-02 19:25 UTC, seb5g commented on src/pymodaq_plugins_signal_recovery/daq_move_plugins/daq_move_Lockin_DSP7265.py
> +            self.status.update(
look at a recent version of the template for more concise way of doing this initialization

2024-12-02 19:25 UTC, seb5g commented on src/pymodaq_plugins_signal_recovery/daq_move_plugins/daq_move_Lockin_DSP7265.py
> +        self.target_frequency = f
do not change current_value to current_frequency, same for target as those are used elsewhere in the parent class!!!!

2024-12-02 19:25 UTC, seb5g commented on src/pymodaq_plugins_signal_recovery/daq_move_plugins/daq_move_Lockin_DSP7265.py
> +        f = (self.check_bound(self.current_frequency + f)
same discussion about current_frequency that should be back to current_value

2024-12-02 19:25 UTC, seb5g commented on src/pymodaq_plugins_signal_recovery/daq_viewer_plugins/plugins_0D/daq_0Dviewer_Lockin_DSP7265.py
> +            self.status.update(
look at a recent version of the plugin template for a more concise way of doing this initialization

2024-12-02 19:25 UTC, seb5g commented on src/pymodaq_plugins_signal_recovery/daq_viewer_plugins/plugins_0D/daq_0Dviewer_Lockin_DSP7265.py
> +        self.data_grabed_signal.emit(data)
look at the template and use dte_signal to emit your data. These are DataToExport object containing DataFromPlugins objects. Look at the plugin template for exemples!

2024-12-02 19:25 UTC, seb5g commented on src/pymodaq_plugins_signal_recovery/hardware/dsp_7265_thread_safe.py
> +    def query(self, **kwargs):
you should probably use the read method name here to make it consistent

2024-12-03 10:38 UTC, louisld commented
I fixed the plugin with latest version of the template. However, I don't have access to the device right now so I need to test the change I made. I will try to do this on Friday.

2024-12-06 10:13 UTC, louisld commented
I have an issue with multiaxes parameters in my actuator. I used `comon_parameters_fun` add the multiaxes parameters. The argument `is_multiaxes` is set to `True` but I only have one label for the axis since the actuator is one axis and the other axis are in viewer.

I saw this line inside the definition of `comon_parameter_fun`: `is_multiaxes = len(axis_names) > 1`. So that means that the argument of the function is not taken into account and my actuator is considered as one axis which cause problems for the master/slave relationship.

2024-12-06 10:55 UTC, louisld commented
Adding a random label in `axis_names` resolve the issue and the plugin works.

2024-12-19 13:14 UTC, seb5g approved these changes

2024-12-19 13:14 UTC, seb5g commented
thx for your work!

2024-12-19 13:15 UTC, merged